// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElButtonGroup: typeof import('element-plus/lib')['ElButtonGroup']
    ElDialog: typeof import('element-plus/lib')['ElDialog']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElTooltip: typeof import('element-plus/lib')['ElTooltip']
    IconMdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    Json: typeof import('./components/json.vue')['default']
    Nav: typeof import('./components/nav.vue')['default']
    SignDialog: typeof import('./components/dialog/signDialog.vue')['default']
    VanImage: typeof import('vant/lib')['Image']
  }
}

export { }
